language: php

php:
  - 5.3
  - 5.4
  - 5.5

script:
  - phpunit -c app/
  - ./codecept run

before_script:
  - wget http://getcomposer.org/composer.phar
  - php composer.phar self-update
  - php composer.phar install
  - ./codecept build
