# Variables that are in this file, can be used in your twig template like {{ theme.foo }}
# Note: If variables do not immediately show up, clear the cache, in the Bolt Backend.
foo: bar

# Choose which image is shown on the frontpage, will be overridden if your homepage record has an image
frontpage_image: base-2016/images/image1.jpg

# Choose which contenttypes are listed on the frontpage
frontpage_contenttypes:
    - entries
#    - pages

# Choose which images are used on listings and record views where the record has no image
images:
    - base-2016/images/image2.jpg
    - base-2016/images/image3.jpg
    - base-2016/images/image4.jpg
