# Optional config file for the theme.

# Variables that are in this file, can be used in your twig template like {{ theme.foo }}
# Note: If variables do not immediately show up, clear the cache, in the Bolt Backend.

foo: bar

# setting the header image. The default images in this theme all came from Pexels: http://pexels.com
headerimage:
    - agriculture-field-grain-1585.jpg
    - beach-dune-field-1710.jpg
    - boat-lake-landing-stage-2535.jpg
    - daisies-flowers-grass-623.jpg
    - dark-clouds-grass-landscape-405.jpg
    - forest-grass-lawn-1826.jpg

# Template filenames. If you 're creating a theme for distribution, you can specify
# the filenames of the templates here. The templates you will set in this config
# file will override the ones in the global app/config/config.yml, so beware!
# maintenance_template: maintenance_default.twig
# homepage_template: index.twig
# record_template: record.twig
# listing_template: listing.twig
# search_results_template: listing.twig

templatefields:
    extrafields.twig:
        section_1:
            type: text
            label: Section 1
        section_2:
            type: text
            label: Section 2
        image:
            type: image

# There can be defined the templates for the template chooser
#templateselect:
#    templates:
#        record:
#            name: 'Template for Records'
#            filename: 'record.twig'