# Optional config file for the theme.

# Variables that are in this file, can be used in your twig template like {{ theme.foo }}
# Note: If variables do not immediately show up, clear the cache, in the Bolt Backend.

foo: bar

# setting the header image. The default images in this theme all came from Pexels: http://pexels.com 
headerimage: 
  - agriculture-field-grain-1585.jpg
  - beach-dune-field-1710.jpg
  - boat-lake-landing-stage-2535.jpg
  - daisies-flowers-grass-623.jpg
  - dark-clouds-grass-landscape-405.jpg
  - forest-grass-lawn-1826.jpg

# Template filenames: 
maintenance_template: maintenance_default.twig
homepage_template: index.twig
record_template: record.twig
listing_template: listing.twig
search_results_template: listing.twig